name: "Hello World"
author: "yzAlvin"
description: "Greet someone and record the time"
inputs:
  input-directory:
    description: "Directory containing markdown"
    required: true
outputs:
  output:
    description: "json of the input"
runs:
  using: "node12"
  main: "dist/index.js"
  post: "commit.sh"
