name: "Markdown metadata to JSON"
author: "yzAlvin"
description: "Turn a collection of markdown with metadata to a json object"
inputs:
  input-directory:
    description: "Directory containing markdown files"
    required: true
  content-field:
    description: "Name of field containing everything other than metadata"
    required: false
    default: "content"
outputs:
  output:
    description: "json array of objects containing metadata"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'book-open'
  color: 'blue'
