on:
  push:
    branches:
      - master

jobs:
  markdown_metadata_to_json_job:
    runs-on: ubuntu-latest
    name: Create json from markdown
    steps:
      - uses: actions/checkout@v2
      - name: Generate JSON from Markdown step
        id: hello
        uses: yzalvin/action-yaml-front-matter@v1
        with:
          input-directory: "./demo"
          # content-field: "description"
      - name: Print the output
        run: echo "The JSON is\n ${{ steps.hello.outputs.output }}"
      - name: Commit files
        run: |
          echo '${{ steps.hello.outputs.output }}' > demo.json
          git config user.email "actions@github.com"
          git config user.name "hehe"
          git add --all
          git commit -m "Update json" || echo "No changes to commit"
          git push
