on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create json from markdown
    steps:
      - uses: actions/checkout@v2
      - name: json from markdown action step
        id: hello
        uses: yzalvin/action-yaml-front-matter@v1
        with:
          input-directory: "./demo"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The JSON is\n ${{ steps.hello.outputs.output }}"
      # - name: Commit
      #   run: |
      #     echo '${{ steps.hello.outputs.output }}' > demo.json
      #     git config user.email "actions@github.com"
      #     git config user.name "hehe"
      #     git add --all
      #     git commit -m "Update json" || echo "No changes to commit"
      #     git push
