on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create json from markdown
    steps:
      - uses: actions/checkout@v2
      - name: json from markdown action step
        id: hello
        uses: yzalvin/action-yaml-front-matter@v1
        with:
          who-to-greet: "yzAlvin"
          input-directory: "./demo"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
