on:
  push:
    branches:
      - master

jobs:
  demo_1:
    runs-on: ubuntu-latest
    name: Create json from yaml front matter demo
    steps:
      - uses: actions/checkout@v2

      - name: Front matter to JSON step
        id: demo
        uses: yzalvin/action-yaml-front-matter@v1.2
        with:
          input-directory: "./demo*"
          content-field: "description"
      - name: Print the output
        run: echo "The JSON is\n ${{ steps.demo.outputs.output }}"

      - name: build jsons
        run: ./create.sh "${{ steps.demo.outputs.output }}"
      - name: Commit files
        run: |
          git config user.email "actions@github.com"
          git config user.name "hehe"
          git add --all
          git commit -m "Update json" || echo "No changes to commit"
          git push
