on:
  push:
    branches:
      - master

jobs:
  demo_1:
    runs-on: ubuntu-latest
    name: Create json from yaml front matter demo
    steps:
      - uses: actions/checkout@v2
      - name: Front matter to JSON step
        id: hello
        uses: yzalvin/action-yaml-front-matter@v1.1
        with:
          input-directory: "./demo"
          content-field: "description"
      - name: Print the output
        run: echo "The JSON is\n ${{ steps.hello.outputs.output }}"
      - name: Commit files
        run: |
          echo '${{ steps.hello.outputs.output }}' > './demo/result.json'
          git config user.email "actions@github.com"
          git config user.name "hehe"
          git add --all
          git commit -m "Update json" || echo "No changes to commit"
          git push
  demo_2:
    runs-on: ubuntu-latest
    name: Create json from yaml front matter demo
    steps:
      - uses: actions/checkout@v2
      - name: Front matter to JSON step
        id: hello
        uses: yzalvin/action-yaml-front-matter@v1.1
        with:
          input-directory: "./demo2"
      - name: Print the output
        run: echo "The JSON is\n ${{ steps.hello.outputs.output }}"
      - name: Commit files
        run: |
          echo '${{ steps.hello.outputs.output }}' > './demo2/result.json'
          git config user.email "actions@github.com"
          git config user.name "hehe"
          git add --all
          git commit -m "Update json" || echo "No changes to commit"
          git push
